#page title
page_title                                : mtdot | Jet Share

# App Info
ios_app_id                                : null

appstore_link                             : null
playstore_link                            : https://play.google.com/store/apps/details?id=mtdot.app.jetshare
presskit_download_link                    : null                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png
app_name                                  : Jet Share
app_price                                 : Free
app_description                           : Fastest sharing app for your Android phone<br/> * Reviewed on <a href='https://taimienphi.vn/download-jet-share-91734'>taimienphi.vn</a>

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : mtdot-dev                                
your_link                                 : https://mtdot-dev.github.io                     
your_city                                 : Ha Noi - Viet Nam                                
email_address                             : son.trt9x@gmail.com
facebook_username                         :                                           
instagram_username                        : null
twitter_username                          : null
github_username                           : mtdot-dev
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Fast
    description                           : Transfer any files with maximum 25MB/s
    fontawesome_icon_name                 : fighter-jet
    
  - title                                 : Offline
    description                           : Work without wifi connection
    fontawesome_icon_name                 : mobile

  - title                                 : Support all file types
    description                           : You can send any kind of files.
    fontawesome_icon_name                 : file


# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown